package com.migrator.core.db.impl.oracle;

import com.migrator.core.db.DbVersionRepository;
import com.migrator.model.MigrationScript;

import java.sql.*;
import java.util.HashSet;
import java.util.Set;

public class OracleDbVersionRepository implements DbVersionRepository {
    private final Connection connection;

    public OracleDbVersionRepository(Connection connection) {
        this.connection = connection;
    }

    @Override
    public Set<String> getAppliedVersions() {
        Set<String> versions = new HashSet<>();

        try {
            ensureMigrationInfrastructure();

            try (PreparedStatement stmt = connection.prepareStatement(
                    "SELECT version FROM schema_migrations"
            )) {
                ResultSet rs = stmt.executeQuery();
                while (rs.next()) {
                    versions.add(rs.getString("version"));
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Failed to fetch applied migrations", e);
        }

        return versions;
    }

    @Override
    public void save(MigrationScript script) {
        try (PreparedStatement stmt = connection.prepareStatement(
                """
                INSERT INTO schema_migrations
                    (version, description, checksum)
                VALUES (?, ?, ?)
                """
        )) {
            stmt.setString(1, script.getVersion());
            stmt.setString(2, script.getDescription());
            stmt.setString(3, script.getChecksum());
            stmt.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException(
                    "Failed to save migration record for version " + script.getVersion(), e
            );
        }
    }

    /**
     * Creates schema_migrations table if it does not exist (Oracle compatible).
     */
    private void ensureMigrationInfrastructure() throws SQLException {

        // 1. schema_migrations table
        if (!tableExists("SCHEMA_MIGRATIONS")) {
            try (Statement stmt = connection.createStatement()) {
                stmt.execute("""
                CREATE TABLE schema_migrations (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    version VARCHAR2(50) NOT NULL UNIQUE,
                    description VARCHAR2(255),
                    applied_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                    checksum VARCHAR2(255)
                )
            """);
            }
        }

        // 2. schema_migration_lock table
        if (!tableExists("SCHEMA_MIGRATION_LOCK")) {
            try (Statement stmt = connection.createStatement()) {
                stmt.execute("""
                CREATE TABLE schema_migration_lock (
                    id NUMBER PRIMARY KEY,
                    locked_at TIMESTAMP
                )
            """);
            }
        }

        // 3. ensure single lock row (id = 1)
        try (PreparedStatement ps = connection.prepareStatement("""
        MERGE INTO schema_migration_lock t
        USING (SELECT 1 AS id FROM dual) s
        ON (t.id = s.id)
        WHEN NOT MATCHED THEN
          INSERT (id, locked_at)
          VALUES (1, SYSTIMESTAMP)
    """)) {
            ps.executeUpdate();
        }
    }

    private boolean tableExists(String tableName) throws SQLException {

        String sql = """
        SELECT COUNT(*) FROM user_tables
        WHERE table_name = ?
    """;

        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, tableName.toUpperCase());

            try (ResultSet rs = ps.executeQuery()) {
                rs.next();
                return rs.getInt(1) > 0;
            }
        }
    }

}
